<a href="https://colab.research.google.com/github/chinwejoseph/Data-Analytics-Master-Project/blob/main/Churners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#The datasets are uploaded into google colab to commence the data prepocessing stage.
#Importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.feature_selection import RFE
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
import tensorflow as tf
from sklearn.metrics import confusion_matrix, roc_curve, auc

In [ ]:
df = pd.read_csv('BankChurners.csv')
df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.999910
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.999940
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.999980
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.999870
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.999980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [ ]:
df2 = df [[ 'Attrition_Flag', 'Customer_Age', 'Gender', 'Education_Level', 'Marital_Status', 'Income_Category']]
df2

,Attrition_Flag,Customer_Age,Gender,Education_Level,Marital_Status,Income_Category
0,Existing Customer,45,M,High School,Married,$60K - $80K
1,Existing Customer,49,F,Graduate,Single,Less than $40K
2,Existing Customer,51,M,Graduate,Married,$80K - $120K
3,Existing Customer,40,F,High School,Unknown,Less than $40K
4,Existing Customer,40,M,Uneducated,Married,$60K - $80K
...,...,...,...,...,...,...
10122,Existing Customer,50,M,Graduate,Single,$40K - $60K
10123,Attrited Customer,41,M,Unknown,Divorced,$40K - $60K
10124,Attrited Customer,44,F,High School,Married,Less than $40K
10125,Attrited Customer,30,M,Graduate,Unknown,$40K - $60K
10126,Attrited Customer,43,F,Graduate,Married,Less than $40K

In [ ]:
df3 = df2.copy()

attrition_flag_map = {'Attrited Customer': 1, 'Existing Customer': 0}
education_level_map = {'Unknown': 0, 'Uneducated': 1, 'High School': 2, 'College': 3, 'Graduate': 4, 'Post-Graduate': 5, 'Doctorate': 6}
marital_status_map = {'Unknown': 0, 'Single': 1, 'Married': 2, 'Divorced': 3}
income_category_map = {'Unknown': 0, 'Less than $40K': 1, '$40K - $60K': 2, '$60K - $80K': 3, '$80K - $120K': 4, '$120K +': 5}
gender_map = {'M': 0, 'F': 1}

df3['Attrition_Flag'] = df3['Attrition_Flag'].map(attrition_flag_map)
df3['Education_Level'] = df3['Education_Level'].map(education_level_map)
df3['Marital_Status'] = df3['Marital_Status'].map(marital_status_map)
df3['Income_Category'] = df3['Income_Category'].map(income_category_map)
df3['Gender'] = df3['Gender'].map(gender_map)
df3

,Attrition_Flag,Customer_Age,Gender,Education_Level,Marital_Status,Income_Category
0,0,45,0,2,2,3
1,0,49,1,4,1,1
2,0,51,0,4,2,4
3,0,40,1,2,0,1
4,0,40,0,1,2,3
...,...,...,...,...,...,...
10122,0,50,0,4,1,2
10123,1,41,0,0,3,2
10124,1,44,1,2,2,1
10125,1,30,0,4,0,2
10126,1,43,1,4,2,1

In [ ]:
# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty list to store accuracy results
accuracy_results = []

# Loop through each column and train/test a logistic regression model
for col in columns:
    X = df3.drop(col, axis=1) # Features
    y = df3[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets
    lr = LogisticRegression(max_iter=10000) # Initialize logistic regression model
    lr.fit(X_train, y_train) # Train model
    y_pred = lr.predict(X_test) # Make predictions on test set

    accuracy = accuracy_score(y_test, y_pred) # Calculate accuracy
    accuracy_results.append(accuracy) # Append accuracy result to list

# Create a table of the accuracy results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results})

print(results_table)

            Column  Accuracy
0     Customer_Age  0.045410
1           Gender  0.880553
2  Education_Level  0.296150
3   Marital_Status  0.457552
4  Income_Category  0.490622

In [ ]:
# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty list to store accuracy results
accuracy_results = []

# Loop through each column and train/test an Adaboost model
for col in columns:
    X = df3.drop(col, axis=1) # Features
    y = df3[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets
    adaboost = AdaBoostClassifier(n_estimators=50, learning_rate=1) # Initialize Adaboost model
    adaboost.fit(X_train, y_train) # Train model
    y_pred = adaboost.predict(X_test) # Make predictions on test set
    accuracy = accuracy_score(y_test, y_pred) # Calculate accuracy
    accuracy_results.append(accuracy) # Append accuracy result to list

# Create a table of the accuracy results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results})

print(results_table)

            Column  Accuracy
0     Customer_Age  0.040967
1           Gender  0.894867
2  Education_Level  0.296150
3   Marital_Status  0.460020
4  Income_Category  0.484205

In [ ]:
# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty list to store accuracy results
accuracy_results = []

# Loop through each column and train/test a random forest model
for col in columns:
    X = df3.drop(col, axis=1) # Features
    y = df3[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets
    rf = RandomForestClassifier(n_estimators=100, random_state=42) # Initialize random forest model with 100 trees
    rf.fit(X_train, y_train) # Train model
    y_pred = rf.predict(X_test) # Make predictions on test set
    accuracy = accuracy_score(y_test, y_pred) # Calculate accuracy
    accuracy_results.append(accuracy) # Append accuracy result to list

# Create a table of the accuracy results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results})

print(results_table)

            Column  Accuracy
0     Customer_Age  0.049852
1           Gender  0.884501
2  Education_Level  0.232478
3   Marital_Status  0.436821
4  Income_Category  0.442744

In [ ]:

# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty list to store accuracy results
accuracy_results = []

# Loop through each column and train/test an SVM model
for col in columns:
    X = df3.drop(col, axis=1) # Features
    y = df3[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets
    clf = svm.SVC() # Initialize SVM model
    clf.fit(X_train, y_train) # Train model
    y_pred = clf.predict(X_test) # Make predictions on test set
    accuracy = accuracy_score(y_test, y_pred) # Calculate accuracy
    accuracy_results.append(accuracy) # Append accuracy result to list

# Create a table of the accuracy results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results})

print(results_table)

            Column  Accuracy
0     Customer_Age  0.048865
1           Gender  0.884995
2  Education_Level  0.296150
3   Marital_Status  0.462488
4  Income_Category  0.415597

In [ ]:
# Create a list of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Loop through each column and train/test an ANN model
results = []
for col in columns:
    # Select the features and target variables
    X = df3.drop([col, 'Attrition_Flag'], axis=1)
    y = df3[col]

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Scale the features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Build the ANN model
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(64, activation='relu', input_dim=X_train.shape[1]))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(32, activation='relu'))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    # Train the model
    model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

    # Test the model and calculate accuracy
    y_pred = model.predict(X_test)
    y_pred = (y_pred > 0.5)
    accuracy = accuracy_score(y_test, y_pred)
    results.append([col, accuracy])

# Print the results in a tabular form
print(pd.DataFrame(results, columns=['Column', 'Accuracy']))

64/64 [==============================] - 0s 2ms/step
64/64 [==============================] - 0s 1ms/step
64/64 [==============================] - 0s 2ms/step
64/64 [==============================] - 0s 1ms/step
64/64 [==============================] - 0s 2ms/step
            Column  Accuracy
0     Customer_Age  0.000000
1           Gender  0.890918
2  Education_Level  0.155972
3   Marital_Status  0.394373
4  Income_Category  0.369694

In [ ]:
df4=df3.copy()
df4

,Attrition_Flag,Customer_Age,Gender,Education_Level,Marital_Status,Income_Category
0,0,45,0,2,2,3
1,0,49,1,4,1,1
2,0,51,0,4,2,4
3,0,40,1,2,0,1
4,0,40,0,1,2,3
...,...,...,...,...,...,...
10122,0,50,0,4,1,2
10123,1,41,0,0,3,2
10124,1,44,1,2,2,1
10125,1,30,0,4,0,2
10126,1,43,1,4,2,1

In [ ]:
# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty lists to store evaluation results
accuracy_results = []
precision_results = []
recall_results = []
f1_results = []

# Loop through each column and train/test a logistic regression model
for col in columns:
    X = df4.drop(col, axis=1) # Features
    y = df4[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets
    lr = LogisticRegression(max_iter=10000) # Initialize logistic regression model
    lr.fit(X_train, y_train) # Train model
    y_pred = lr.predict(X_test) # Make predictions on test set

    accuracy = accuracy_score(y_test, y_pred) # Calculate accuracy
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    accuracy_results.append(accuracy) # Append accuracy result to list
    precision_results.append(precision)
    recall_results.append(recall)
    f1_results.append(f1)

# Create a table of the evaluation results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results, 'Precision': precision_results, 'Recall': recall_results, 'F1': f1_results})

print(results_table)

            Column  Accuracy  Precision    Recall        F1
0     Customer_Age  0.045410   0.045410  0.045410  0.027138
1           Gender  0.880553   0.880553  0.880553  0.880545
2  Education_Level  0.296150   0.296150  0.296150  0.135331
3   Marital_Status  0.457552   0.457552  0.457552  0.332649
4  Income_Category  0.490622   0.490622  0.490622  0.372585

In [ ]:

# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty lists to store evaluation results
accuracy_results = []
precision_results = []
recall_results = []
f1_results = []
# Loop through each column and train/test an Adaboost model
for col in columns:
    X = df4.drop(col, axis=1) # Features
    y = df4[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets

    # Initialize Adaboost model
    adaboost = AdaBoostClassifier(n_estimators=50, random_state=42)
    # Train Adaboost model
    adaboost.fit(X_train, y_train)
    # Make predictions on test set
    y_pred = adaboost.predict(X_test)
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Append evaluation results to lists
    accuracy_results.append(accuracy)
    precision_results.append(precision)
    recall_results.append(recall)
    f1_results.append(f1)

# Create a table of the evaluation results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results, 'Precision': precision_results, 'Recall': recall_results, 'F1': f1_results})
print(results_table)

            Column  Accuracy  Precision    Recall        F1
0     Customer_Age  0.040967   0.040967  0.040967  0.016231
1           Gender  0.894867   0.894867  0.894867  0.893559
2  Education_Level  0.296150   0.296150  0.296150  0.139176
3   Marital_Status  0.460020   0.460020  0.460020  0.372784
4  Income_Category  0.484205   0.484205  0.484205  0.413498

In [ ]:
# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty lists to store evaluation results
accuracy_results = []
precision_results = []
recall_results = []
f1_results = []

# Loop through each column and train/test a Random Forest model
for col in columns:
    X = df4.drop(col, axis=1) # Features
    y = df4[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets

    # Initialize Random Forest model
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    # Train Random Forest model
    rf.fit(X_train, y_train)
    # Make predictions on test set
    y_pred = rf.predict(X_test)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=1)
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Append evaluation results to lists
    accuracy_results.append(accuracy)
    precision_results.append(precision)
    recall_results.append(recall)
    f1_results.append(f1)

# Create a table of the evaluation results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results, 'Precision': precision_results, 'Recall': recall_results, 'F1': f1_results})
print(results_table)

            Column  Accuracy  Precision    Recall        F1
0     Customer_Age  0.049852   0.049852  0.049852  0.042089
1           Gender  0.884501   0.884501  0.884501  0.884189
2  Education_Level  0.232478   0.232478  0.232478  0.192348
3   Marital_Status  0.436821   0.436821  0.436821  0.414079
4  Income_Category  0.442744   0.442744  0.442744  0.412910

In [ ]:
# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty lists to store evaluation results
accuracy_results = []
precision_results = []
recall_results = []
f1_results = []

# Loop through each column and train/test an SVM model
for col in columns:
    X = df4.drop(col, axis=1) # Features
    y = df4[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets

    # Initialize SVM model
    svm_model = SVC(kernel='linear', random_state=42)
    # Train SVM model
    svm_model.fit(X_train, y_train)
    # Make predictions on test set
    y_pred = svm_model.predict(X_test)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=1)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=1)

    # Append evaluation results to lists
    accuracy_results.append(accuracy)
    precision_results.append(precision)
    recall_results.append(recall)
    f1_results.append(f1)

# Create a table of the evaluation results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results, 'Precision': precision_results, 'Recall': recall_results, 'F1': f1_results})
print(results_table)

            Column  Accuracy  Precision    Recall        F1
0     Customer_Age  0.045903   0.045903  0.045903  0.021932
1           Gender  0.883514   0.883514  0.883514  0.883011
2  Education_Level  0.296150   0.296150  0.296150  0.135331
3   Marital_Status  0.454097   0.454097  0.454097  0.283618
4  Income_Category  0.487167   0.487167  0.487167  0.349099

In [ ]:
# List of columns to train and test
columns = ['Customer_Age','Gender', 'Education_Level', 'Marital_Status', 'Income_Category']

# Initialize empty lists to store evaluation results
accuracy_results = []
precision_results = []
recall_results = []
f1_results = []

# Import required packages for ANN model
from keras.models import Sequential
from keras.layers import Dense

# Loop through each column and train/test an ANN model
for col in columns:
    X = df4.drop(col, axis=1) # Features
    y = df4[col] # Target variable
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split data into train/test sets

    # Define ANN model
    model = Sequential()
    model.add(Dense(32, activation='relu', input_dim=X_train.shape[1]))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    # Compile ANN model
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    # Train ANN model
    model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

    # Make predictions on test set
    y_pred = model.predict(X_test)
    y_pred = (y_pred > 0.5).astype(int)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro', zero_division=0)
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    # Append evaluation results to lists
    accuracy_results.append(accuracy)
    precision_results.append(precision)
    recall_results.append(recall)
    f1_results.append(f1)

# Create a table of the evaluation results
results_table = pd.DataFrame({'Column': columns, 'Accuracy': accuracy_results, 'Precision': precision_results, 'Recall': recall_results, 'F1': f1_results})

print(results_table)

64/64 [==============================] - 0s 1ms/step
64/64 [==============================] - 0s 1ms/step
64/64 [==============================] - 0s 2ms/step
64/64 [==============================] - 0s 1ms/step
64/64 [==============================] - 0s 2ms/step
            Column  Accuracy  Precision    Recall        F1
0     Customer_Age  0.000000   0.000000  0.000000  0.000000
1           Gender  0.889931   0.889931  0.889931  0.888146
2  Education_Level  0.155972   0.155972  0.155972  0.042090
3   Marital_Status  0.394373   0.394373  0.394373  0.223083
4  Income_Category  0.369694   0.369694  0.369694  0.199568

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif

# Select the desired columns
df5 = df3[['Attrition_Flag', 'Customer_Age', 'Gender', 'Education_Level', 'Marital_Status', 'Income_Category']]

# Split the data into training and testing sets
X = df5.drop('Attrition_Flag', axis=1)
y = df5['Attrition_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Feature selection
selector = SelectKBest(f_classif, k=1)
selector.fit(X_train, y_train)
important_feature_index = selector.get_support(indices=True)
important_feature = X.columns[important_feature_index]

# Train the model
model = MLPClassifier(hidden_layer_sizes=(10, 5), max_iter=1000, random_state=42)
model.fit(X_train[:, important_feature_index], y_train)

# Test the model
y_pred = model.predict(X_test[:, important_feature_index])

# Evaluate the model
accuracy = model.score(X_test[:, important_feature_index], y_test)
precision = metrics.precision_score(y_test, y_pred, pos_label=1, zero_division=0)
recall = metrics.recall_score(y_test, y_pred, pos_label=1)
f1 = metrics.f1_score(y_test, y_pred, pos_label=1)

print("Important feature: {}".format(important_feature[0]))
print("Accuracy: {:.2f}".format(accuracy))
print("Precision: {:.2f}".format(precision))
print("Recall: {:.2f}".format(recall))
print("F1 Score: {:.2f}".format(f1))

Important feature: Gender
Accuracy: 0.84
Precision: 0.00
Recall: 0.00
F1 Score: 0.00

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
import pandas as pd
from sklearn.model_selection import train_test_split

# Select the desired columns
df5 = df3[['Attrition_Flag', 'Customer_Age', 'Gender', 'Education_Level', 'Marital_Status', 'Income_Category']]

# Split the data into training and testing sets
X = df5.drop('Attrition_Flag', axis=1)
y = df5['Attrition_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Feature selection
selector = SelectKBest(f_classif, k=1)
selector.fit(X_train, y_train)
important_feature_index = selector.get_support(indices=True)
important_feature = X.columns[important_feature_index]

# Train the model
model = MLPClassifier(hidden_layer_sizes=(10, 5), max_iter=1000, random_state=42)
model.fit(X_train[:, important_feature_index], y_train)

# Test the model
y_pred = model.predict(X_test[:, important_feature_index])

# Evaluate the model
accuracy = model.score(X_test[:, important_feature_index], y_test)
precision = metrics.precision_score(y_test, y_pred, pos_label=1, zero_division=0)
recall = metrics.recall_score(y_test, y_pred, pos_label=1)
f1 = metrics.f1_score(y_test, y_pred, pos_label=1)

print("Important feature: {}".format(important_feature[0]))
print("Accuracy: {:.2f}".format(accuracy))
print("Precision: {:.2f}".format(precision))
print("Recall: {:.2f}".format(recall))
print("F1 Score: {:.2f}".format(f1))

Important feature: Gender
Accuracy: 0.84
Precision: 0.00
Recall: 0.00
F1 Score: 0.00

In [ ]:
# Calculate the total number of female customers
total_female_customers = len(df5[df5['Gender'] == 1])

# Calculate the number of attrited female customers
attrited_female_customers = len(df5[(df5['Gender'] == 1) & (df5['Attrition_Flag'] == 1)])

# Calculate the number of existing female customers
existing_female_customers = len(df5[(df5['Gender'] == 1) & (df5['Attrition_Flag'] == 0)])

# Calculate the percentage of attrited female customers
attrited_female_percentage = (attrited_female_customers / total_female_customers) * 100

# Calculate the percentage of existing female customers
existing_female_percentage = (existing_female_customers / total_female_customers) * 100

print("Percentage of attrited female customers: {:.2f}%".format(attrited_female_percentage))
print("Percentage of existing female customers: {:.2f}%".format(existing_female_percentage))

Percentage of attrited female customers: 17.36%
Percentage of existing female customers: 82.64%

In [ ]:
# Count the number of male customers who attrited and who are existing
male_attrited = df5[(df5['Gender'] == 0) & (df5['Attrition_Flag'] == 1)]['Attrition_Flag'].count()
male_existing = df5[(df5['Gender'] == 0) & (df5['Attrition_Flag'] == 0)]['Attrition_Flag'].count()

# Calculate the percentage of male customers who attrited and who are existing
male_attrition_percentage = (male_attrited / df5[df5['Gender'] == 1]['Attrition_Flag'].count()) * 100
male_existing_percentage = (male_existing / df5[df5['Gender'] == 1]['Attrition_Flag'].count()) * 100

# Print the results
print("Percentage of male customers who attrited: {:.2f}%".format(male_attrition_percentage))
print("Percentage of male customers who are existing: {:.2f}%".format(male_existing_percentage))

Percentage of male customers who attrited: 13.01%
Percentage of male customers who are existing: 76.00%

df6 = df4.copy()
df6

In [ ]:
df6 = df4.copy()
df6

,Attrition_Flag,Customer_Age,Gender,Education_Level,Marital_Status,Income_Category
0,0,45,0,2,2,3
1,0,49,1,4,1,1
2,0,51,0,4,2,4
3,0,40,1,2,0,1
4,0,40,0,1,2,3
...,...,...,...,...,...,...
10122,0,50,0,4,1,2
10123,1,41,0,0,3,2
10124,1,44,1,2,2,1
10125,1,30,0,4,0,2
10126,1,43,1,4,2,1

In [ ]:
# Select the desired columns
df6 = df6[['Attrition_Flag', 'Customer_Age', 'Gender', 'Education_Level', 'Marital_Status', 'Income_Category']]

# Split the data into training and testing sets
X = df6.drop('Attrition_Flag', axis=1)
y = df6['Attrition_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Get feature importances
importances = model.feature_importances_

# Print feature importances
for feature, importance in zip(X.columns, importances):
    print("Feature: {}, Importance: {:.2f}".format(feature, importance))

# Select important features
important_features = X.columns[importances > 0.05]

# Train the model with important features
X_train_imp = X_train[important_features]
X_test_imp = X_test[important_features]
model_imp = RandomForestClassifier(random_state=42)
model_imp.fit(X_train_imp, y_train)

# Test the model with important features
y_pred_imp = model_imp.predict(X_test_imp)

# Evaluate the model with important features
accuracy = accuracy_score(y_test, y_pred_imp)
precision = precision_score(y_test, y_pred_imp, pos_label=1)
recall = recall_score(y_test, y_pred_imp, pos_label=1)
f1 = f1_score(y_test, y_pred_imp, pos_label=1)

print("Important features: {}".format(important_features))
print("Accuracy: {:.2f}".format(accuracy))
print("Precision: {:.2f}".format(precision))
print("Recall: {:.2f}".format(recall))
print("F1 Score: {:.2f}".format(f1))

Feature: Customer_Age, Importance: 0.61
Feature: Gender, Importance: 0.01
Feature: Education_Level, Importance: 0.17
Feature: Marital_Status, Importance: 0.10
Feature: Income_Category, Importance: 0.10
Important features: Index(['Customer_Age', 'Education_Level', 'Marital_Status', 'Income_Category'], dtype='object')
Accuracy: 0.80
Precision: 0.14
Recall: 0.05
F1 Score: 0.07